In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

In [2]:
df = pd.read_csv('../input/digit-recognizer/train.csv')

In [3]:
df

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [4]:
df.isnull().sum()

label       0
pixel0      0
pixel1      0
pixel2      0
pixel3      0
           ..
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 785, dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB


In [6]:
df.describe()

label   pixel0   pixel1   pixel2   pixel3   pixel4   pixel5  \
count  42000.000000  42000.0  42000.0  42000.0  42000.0  42000.0  42000.0   
mean       4.456643      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.887730      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

        pixel6   pixel7   pixel8  ...      pixel774      pixel775  \
count  42000.0  42000.0  42000.0  ...  42000.000000  42000.000000   
mean       0.0      0.0      0.0  ...      0.219286      0.117095   
std        0.0      0.0      0.0  ...      6.312890      4.633819   
min        0.0      0.0      0.0  ...      0.000000      0.000000   
25%        0.0      0.0      0.0  ...      0.000000      0.000000   
50%        0.0      0.0      0.0  ...      0.000000      0.000000   
75%        0.0      0.0      0.0  ...      0.000000      0.000000   
max        0.0      0.0      0.0  ...    254.000000    254.000000   

           pixel776     pixel777      pixel778      pixel779  pixel780  \
count  42000.000000  42000.00000  42000.000000  42000.000000   42000.0   
mean       0.059024      0.02019      0.017238      0.002857       0.0   
std        3.274488      1.75987      1.894498      0.414264       0.0   
min        0.000000      0.00000      0.000000      0.000000       0.0   
25%        0.000000      0.00000      0.000000      0.000000       0.0   
50%        0.000000      0.00000      0.000000      0.000000       0.0   
75%        0.000000      0.00000      0.000000      0.000000       0.0   
max      253.000000    253.00000    254.000000     62.000000       0.0   

       pixel781  pixel782  pixel783  
count   42000.0   42000.0   42000.0  
mean        0.0       0.0       0.0  
std         0.0       0.0       0.0  
min         0.0       0.0       0.0  
25%         0.0       0.0       0.0  
50%         0.0       0.0       0.0  
75%         0.0       0.0       0.0  
max         0.0       0.0       0.0  

[8 rows x 785 columns]

In [7]:
X = df.drop('label',axis=1)

In [8]:
y = df['label']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.67, random_state=42)

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
tree = DecisionTreeClassifier()

In [13]:
tree = tree.fit(X_train,y_train)

In [14]:
predict = tree.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix

In [16]:
print(classification_report(y_test,predict))
print(confusion_matrix(y_test,predict))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89      2774
           1       0.93      0.94      0.94      3126
           2       0.82      0.80      0.81      2858
           3       0.81      0.78      0.79      2935
           4       0.84      0.81      0.82      2758
           5       0.72      0.77      0.75      2510
           6       0.84      0.85      0.85      2771
           7       0.85      0.87      0.86      2910
           8       0.77      0.74      0.76      2731
           9       0.77      0.80      0.78      2767

    accuracy                           0.83     28140
   macro avg       0.83      0.83      0.82     28140
weighted avg       0.83      0.83      0.83     28140

[[2463    3   30   44   18   51   73   24   36   32]
 [   2 2927   34   25   13   35   14   21   45   10]
 [  58   40 2283   93   42   70   87   74   80   31]
 [  21   30   89 2282   26  201   28   66  110   82]
 [  24   14   35   24 2225   

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
ft = RandomForestClassifier()

In [19]:
ft = ft.fit(X_train,y_train)

In [20]:
prediction = ft.predict(X_test)

In [21]:
ft.score(X_train,y_train)

1.0

In [22]:
print(classification_report(y_test,prediction))
print(confusion_matrix(y_test,prediction))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98      2774
           1       0.97      0.98      0.98      3126
           2       0.95      0.94      0.95      2858
           3       0.93      0.93      0.93      2935
           4       0.96      0.95      0.95      2758
           5       0.95      0.94      0.94      2510
           6       0.96      0.97      0.97      2771
           7       0.96      0.95      0.96      2910
           8       0.94      0.93      0.93      2731
           9       0.92      0.93      0.93      2767

    accuracy                           0.95     28140
   macro avg       0.95      0.95      0.95     28140
weighted avg       0.95      0.95      0.95     28140

[[2733    0    3    2    2    4   13    2   13    2]
 [   0 3065   16   16    3    5    8    7    4    2]
 [  12   13 2693   24   27    4   24   31   23    7]
 [   5    7   41 2735    5   54    5   21   39   23]
 [   5    4    6    1 2610   

In [23]:
result = pd.DataFrame({'ImageId': np.arange(1, (prediction.shape[0] + 1)), 'Label': prediction})
result.to_csv('result.csv', index=False)
print('Done')

Done
